import { Routes } from '@angular/router';

export const routes: Routes = [
  { path: '', loadComponent: () => import('./dashboard/dashboard.component').then(m => m.DashboardComponent) },
  { path: 'todo', loadComponent: () => import('./todo/todo.component').then(m => m.TodoComponent) },
  { path: 'ip-address', loadComponent: () => import('./ip-address/ip-address.component').then(m => m.IpAddressComponent) },
  { path: 'url-shortener', loadComponent: () => import('./url-shortener/url-shortener.component').then(m => m.UrlShortenerComponent) },
  { path: 'timer', loadComponent: () => import('./timer/timer.component').then(m => m.TimerComponent) },
  { path: 'base64', loadComponent: () => import('./base64/base64.component').then(m => m.Base64Component) },
  { path: 'json-formatter', loadComponent: () => import('./json-formatter/json-formatter.component').then(m => m.JsonFormatterComponent) },
  { path: 'qr-generator', loadComponent: () => import('./qr-generator/qr-generator.component').then(m => m.QrGeneratorComponent) },
  { path: 'color-picker', loadComponent: () => import('./color-picker/color-picker.component').then(m => m.ColorPickerComponent) },
  { path: 'text-tools', loadComponent: () => import('./text-tools/text-tools.component').then(m => m.TextToolsComponent) },
  { path: 'jwt-debugger', loadComponent: () => import('./jwt-debugger/jwt-debugger.component').then(m => m.JwtDebuggerComponent) },
  { path: 'hash-generator', loadComponent: () => import('./hash-generator/hash-generator.component').then(m => m.HashGeneratorComponent) },
  { path: 'uuid-generator', loadComponent: () => import('./uuid-generator/uuid-generator.component').then(m => m.UuidGeneratorComponent) },
  { path: 'timestamp-converter', loadComponent: () => import('./timestamp-converter/timestamp-converter.component').then(m => m.TimestampConverterComponent) },
  { path: 'url-encoder', loadComponent: () => import('./url-encoder/url-encoder.component').then(m => m.UrlEncoderComponent) },
  { path: 'css-generator', loadComponent: () => import('./css-generator/css-generator.component').then(m => m.CssGeneratorComponent) },
  { path: 'dummy-data', loadComponent: () => import('./dummy-data/dummy-data.component').then(m => m.DummyDataComponent) },
  { path: 'markdown-previewer', loadComponent: () => import('./markdown-previewer/markdown-previewer.component').then(m => m.MarkdownPreviewerComponent) },
  { path: 'news', loadComponent: () => import('./news/news').then(m => m.News) },
  { path: 'resources', loadComponent: () => import('./resources/resources').then(m => m.Resources) },
  { path: 'photo-editor', loadComponent: () => import('./photo-editor/photo-editor').then(m => m.PhotoEditor) },
  { path: 'audio-converter', loadComponent: () => import('./audio-converter/audio-converter').then(m => m.AudioConverter) },
  { path: 'pdf-tools', loadComponent: () => import('./pdf-tools/pdf-tools').then(m => m.PdfTools) },
  { path: 'games', loadComponent: () => import('./games/games-dashboard/games-dashboard').then(m => m.GamesDashboardComponent) },
  { path: 'games/snake', loadComponent: () => import('./games/snake-and-eggs/snake-and-eggs').then(m => m.SnakeAndEggsComponent) },
  { path: 'games/bounce', loadComponent: () => import('./games/bounce/bounce.component').then(m => m.BounceComponent) },
  { path: 'games/tic-tac-toe', loadComponent: () => import('./games/tic-tac-toe/tic-tac-toe.component').then(m => m.TicTacToeComponent) },
  { path: 'games/angry-birds', loadComponent: () => import('./games/angry-birds/angry-birds.component').then(m => m.AngryBirdsComponent) },
  { path: 'games/tetris', loadComponent: () => import('./games/tetris/tetris.component').then(m => m.TetrisComponent) },
  { path: 'games/space-blaster', loadComponent: () => import('./games/space-blaster/space-blaster.component').then(m => m.SpaceBlasterComponent) },
  { path: 'games/mario-runner', loadComponent: () => import('./games/mario-runner/mario-runner.component').then(m => m.MarioRunnerComponent) },
  { path: '**', redirectTo: '/' }
];
