export const quotes = [
    "It works on my machine.",
    "Why do programmers prefer dark mode? Because light attracts bugs.",
    "There are only two hard things in Computer Science: cache invalidation, naming things, and off-by-one errors.",
    "A SQL query walks into a bar and asks two tables: Can I join you?",
    "The best thing about a Boolean is even if you are wrong, you are only off by a bit.",
    "To understand recursion, you must first understand recursion.",
    "Real programmers count from 0.",
    "99 little bugs in the code, take one down, patch it around, 127 little bugs in the code.",
    "Git commit messages: 'final fix', 'final final fix', 'ok really final fix'.",
    "Programming is 10% writing code and 90% understanding why it doesn’t work.",
    "Debugging: Being the detective in a crime movie where you are also the murderer.",
    "Java and JavaScript are like Car and Carpet.",
    "Code never lies, comments sometimes do.",
    "Weeks of coding can save you hours of planning.",
    "First, solve the problem. Then, write the code.",
    "Good code is its own best documentation.",
    "A programmer’s wife tells him to go to the store: Buy a loaf of bread, and if they have eggs, buy a dozen. He comes home with 12 loaves of bread.",
    "There is no place like 127.0.0.1.",
    "Programmer: I have a joke about UDP, but you might not get it.",
    "A bug is not a mistake. It’s an undocumented feature.",
    "With great power comes great responsibility — and a lot of stack traces.",
    "The cloud is just someone else’s computer.",
    "Don’t worry, it’s only temporary… unless it works.",
    "There are two types of people: those who can extrapolate from incomplete data.",
    "Java: Write once, debug everywhere.",
    "I don’t care if it works on your machine! We’re not shipping your machine!",
    "Copy and paste is a design pattern.",
    "Keyboard not found. Press F1 to continue.",
    "Documentation is like sex: when it’s good, it’s very good; when it’s bad, it’s better than nothing.",
    "Artificial intelligence is no match for natural stupidity.",
    "A programmer is a machine that turns coffee into code.",
    "I’d love to change the world, but they won’t give me the source code.",
    "The code is always greener on the other side of the fence.",
    "Talk is cheap. Show me the code.",
    "Walking on water and developing software from a specification are easy if both are frozen.",
    "Software and cathedrals are much the same — first we build them, then we pray.",
    "Programming without caffeine is like a computer without electricity.",
    "Hardware: the part of the computer you can kick.",
    "Software: stuff that doesn’t work yet.",
    "Never trust a computer you can’t throw out a window.",
    "Beware of programmers who carry screwdrivers.",
    "The best error message is the one that never shows up.",
    "Every time you write code, somewhere a QA engineer cries.",
    "Sudo make me a sandwich.",
    "Unix is user-friendly; it’s just very selective about who its friends are.",
    "A good programmer looks both ways before crossing a one-way street.",
    "Algorithm: word used by programmers when they don’t want to explain what they did.",
    "Programming is like writing a book… except if you miss a single comma on page 126, the whole thing makes no sense.",
    "In order to understand recursion, you must first… oh wait.",
    "There is an ‘I’ in ‘team’. It’s hidden in the A/I module.",
    "God is real… unless declared integer.",
    "A programmer had a problem. He thought, ‘I know, I’ll use regular expressions.’ Now he has two problems.",
    "Computers make very fast, very accurate mistakes.",
    "If debugging is the process of removing bugs, then programming must be the process of putting them in.",
    "Don’t explain your code: it was hard to write, it should be hard to understand.",
    "Software doesn’t fail — it just features unexpectedly.",
    "In C we trust; everyone else must provide source code.",
    "Linux is only free if your time has no value.",
    "To err is human, to blame it on a computer is even more human.",
    "A computer program does what you tell it to do, not what you want it to do.",
    "Never underestimate the bandwidth of a station wagon full of tapes hurtling down the highway.",
    "If at first you don’t succeed; call it version 1.0.",
    "Java developers wear glasses because they can’t C#.",
    "It’s not a bug — it’s a feature request.",
    "I just got fired from the keyboard factory. They said I wasn’t putting in enough shifts.",
    "Computers are like air conditioners: they stop working when you open Windows.",
    "My code doesn’t work, I have no idea why. My code works, I have no idea why.",
    "Your code is like a poem… a really bad one.",
    "Whitespace is your friend. Unless it’s in Python.",
    "In programming, ‘Hello World’ is proof of life.",
    "The problem with troubleshooting is that sometimes trouble shoots back.",
    "Why did the programmer quit his job? He didn’t get arrays.",
    "Never test for an error condition you don’t know how to handle.",
    "A day without sunshine is like, you know, night. A day without semicolons is like, you know, Python.",
    "Code fast, debug faster.",
    "Programmer’s diet: Coffee, Pizza, Repeat.",
    "Stack Overflow: where your code goes to cry for help.",
    "Your password must contain an uppercase letter, a lowercase letter, a number, a haiku, a special character, and a blood sacrifice.",
    "In theory, theory and practice are the same. In practice, they’re not.",
    "You can’t have great software without a great team… and coffee.",
    "Debugging is like being the detective in your own murder mystery.",
    "Code never rusts. Unless it’s in JavaScript.",
    "JavaScript is weird: [] + [] = '', [] + {} = '[object Object]', {} + [] = 0.",
    "A clean house is a sign of a broken computer.",
    "Don’t worry if it doesn’t work right. If everything did, you’d be out of a job.",
    "The best programmers are lazy. They automate everything.",
    "Software development is the art of creating bugs you don’t know about.",
    "A program is never finished until the programmer dies.",
    "Commit early, commit often, regret always.",
    "Version control: because we can’t trust ourselves.",
    "Why do Java developers wear glasses? Because they don’t C#.",
    "Never ask a programmer for directions. You’ll get lost in the logic.",
    "Programming is easy. It’s the documentation that’s hard.",
    "The only constant in programming is change.",
    "Never underestimate the power of ‘Ctrl+C’ and ‘Ctrl+V’.",
    "An infinite loop walks into a bar. Bartender says: I’m gonna stop you right there.",
    "When in doubt, brute force it.",
    "Code is like humor. When you have to explain it, it’s bad.",
    "There’s no place like production at 2 AM.",
    "Eat, Sleep, Code, Repeat.",
    "Why did the JavaScript developer go broke? Because he kept working for null.",
    "JavaScript is like a kid: It doesn’t follow rules, but somehow it still works.",
    "[] + [] = '' ; [] + {} = '[object Object]' ; {} + [] = 0 → JavaScript: 'Don’t question me, mortal.'",
    "Why did the developer hate using var? Because it was too scope-y.",
    "JavaScript: 'I can do anything!' — TypeScript: 'But… should you?'",
    "How do you comfort a JavaScript bug? You console it.",
    "Why was the JavaScript function sad? It didn’t get called.",
    "JavaScript developers never die — they just get undefined.",
    "Promises in JavaScript: 'I promise I’ll call you back… maybe.'",
    "What’s the object-oriented way to get wealthy? Inheritance.",
    "Why did the async function break up with the callback? Because it was tired of being kept waiting.",
    "What’s a JavaScript developer’s favorite coffee? Java.",
    "Why did the node server cross the road? To handle the next request.",
    "I like my code like I like my toast: with no bugs.",
    "NaN === NaN is false. JavaScript: 'Logic is optional.'",
    "Why did the front-end developer quit? He didn’t get arrays.",
    "What’s a JavaScript ninja’s favorite weapon? The spread operator (...).",
    "Why did JSON go to therapy? Because it had too many issues with its parents.",
    "JavaScript loves relationships: it always wants a callback.",
    "Why was ES6 afraid of ES7? Because ES7 had async/await.",
    "JavaScript developers: experts in turning coffee into semicolons.",
    "Why don’t JavaScript arrays like math? Because they start counting from zero.",
    "What’s a JavaScript bug’s favorite sport? Catch.",
    "Why did the web developer go broke? Because he used free() too much.",
    "JavaScript devs don’t like nature — too many bugs.",
    "What do JavaScript and teenage drama have in common? Too many promises and not enough resolutions.",
    "Why did the developer switch to TypeScript? Because he wanted a type of security.",
    "JavaScript date objects: making time travel possible since 1995.",
    "How do you kill a JavaScript bug? With console.log.",
    "What’s a JavaScript developer’s favorite game? Call of Duty.",
    "Why did the JS dev keep his job? Because he had closures.",
    "How do JavaScript developers like their steak? Medium rare, but mostly undefined.",
    "Why did React break up with Angular? It didn’t find the right framework.",
    "How many JavaScript devs does it take to change a light bulb? None, they just use dark mode.",
    "Why did the JavaScript function need therapy? It had too many side effects.",
    "How do you find a JavaScript developer in a crowd? Just yell 'undefined' and see who looks up.",
    "JavaScript is like a magician: it makes types disappear.",
    "What’s JavaScript’s favorite band? Foo Bar Fighters.",
    "Why don’t JavaScript devs trust numbers? Because they’re not integers.",
    "What’s a JavaScript variable’s favorite vacation spot? The heap.",
    "JavaScript: where truthy and falsy are a lifestyle, not logic.",
    "Why was the JavaScript object always calm? It was immutable.",
    "How do you calm a crying JavaScript array? Push a new element into it.",
    "What did the JavaScript function say to its friend? 'You complete me… with arguments.'",
    "JavaScript devs measure time in console.logs, not seconds.",
    "Why was the JS class nervous? It didn’t know if it was static or dynamic.",
    "Why do JavaScript devs love memes? Because everything is relatable.",
    "What’s a JavaScript developer’s worst nightmare? The dreaded 'Cannot read property of undefined'.",
    "JavaScript’s motto: 'If it looks wrong but works, it’s probably right.'",
    "Why do JavaScript objects hate Christmas? Because they get stringified.",
    "Why do Python programmers prefer snake_case? Because they can’t camelCase a snake.",
    "Python: 'Indentation is everything.' — Newbie: 'So… my career ends because of a single space?'",
    "A JavaScript dev says: 'We use curly braces {} to define blocks.' — Python replies: 'Hold my whitespace.'",
    "In Python, 'import antigravity' actually works. That’s why Python devs float around feeling superior.",
    "Python is like English: Easy to read, but sometimes you still don’t get the meaning.",
    "Why was the Python developer broke? Because he used all his cache.",
    "Why did the Python developer leave the party? Because he couldn’t find his class.",
    "Python devs don’t need braces — they have strong indentation.",
    "Why don’t Python devs ever get lost? Because they always follow the path variable.",
    "What’s Python’s favorite snake joke? 'I’m constricted by indentation.'",
    "Why did the Python dictionary break up with the list? It couldn’t handle the keys.",
    "Python developers are zen: import this.",
    "Why do Python devs love nature? Because of turtle graphics.",
    "What’s a Python dev’s favorite breakfast? Eggs and exceptions.",
    "Why did the Python program crash? It had too many exceptions to handle.",
    "Why did the Python function feel lonely? Because it had no arguments.",
    "Why are Python loops so calming? Because they’re for-each one of us.",
    "How does Python say sorry? With a try/except.",
    "Why do Python devs carry maps? Because they love dictionaries.",
    "What’s Python’s favorite movie? The Life of Pi.",
    "Why did the Python developer refuse to play cards? He was afraid of the tuple shuffle.",
    "What’s Python’s favorite holiday? Easter — because of eggs.",
    "Python devs don’t argue, they just raise exceptions.",
    "Why did the Python variable cross the road? To get to the other namespace.",
    "Python programmers aren’t lazy — they’re just using list comprehensions.",
    "Why did Python break up with Java? Too many braces.",
    "What’s Python’s favorite music genre? Lo-fi loops.",
    "Python devs don’t have bugs, they have unexpected indentations.",
    "Why did the Python script sleep? To await its destiny.",
    "Why are Python devs bad at relationships? Too many dependencies.",
    "Python devs don’t cry — they print(':'')'.",
    "What’s a Python module’s favorite snack? Chips… import chips.",
    "Why do Python devs love generators? Because they yield results.",
    "What did the Python string say to the integer? 'You can’t handle me without casting.'",
    "Why don’t Python devs like long arguments? Because they prefer kwargs.",
    "Python devs don’t use magic — they use __magic__ methods.",
    "Why did the Python list stay calm? Because it was immutable… wait, nope.",
    "Why do Python devs make bad magicians? Because they reveal all with print().",
    "What’s Python’s dating advice? Just keep it simple and whitespace friendly.",
    "Python developers don’t need therapists. They just pip install happiness.",
    "Why did the Python class go to school? To get more methods.",
    "Python’s favorite social media? Reddit — it loves indentation.",
    "Why don’t Python devs play hide and seek? Because everything is self.",
    "What’s a Python exception’s favorite sport? Try/except/throw.",
    "Why did the Python dictionary go bankrupt? Because it lost its keys.",
    "Python: the only snake people love keeping in their computers.",
    "Why did the Python script act lazy? Because it used async all the time.",
    "Why do Python devs love memes? Because they always get the reference (import memes).",
    "Why did the Python loop break? Because it couldn’t continue.",
    "Python’s motto: 'Whitespace is mightier than the brace.'"
]

